"""pass secure migration

Revision ID: 4bf32641e8db
Revises: 2fdd6ca93014
Create Date: 2018-04-11 13:10:41.334785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4bf32641e8db'
down_revision = '2fdd6ca93014'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('pass_secure', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'pass_secure')
    # ### end Alembic commands ###
